apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cz8ybbeyk-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cz8ybbeyk-java-quarkus-gitops